# Generated by Django 5.2.3 on 2025-10-24 06:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_type', models.CharField(choices=[('self', 'Self Earned'), ('referral', 'Referral Earned')], default='self', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_commissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
            },
        ),
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('referral_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('daily_task_limit', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Setting',
                'verbose_name_plural': 'Commission Settings',
            },
        ),
    ]
