# Generated by Django 5.2.3 on 2025-10-24 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(help_text='The task number that triggers this stoppoint.')),
                ('required_balance', models.DecimalField(decimal_places=2, help_text='The balance the user must have to clear this stoppoint.', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='The current status of the stoppoint.', max_length=10)),
                ('order', models.PositiveIntegerField(help_text='The sequential order of the stoppoint (e.g., 1, 2, 3...).')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stoppoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stop Point Rule',
                'verbose_name_plural': 'Stop Point Rules',
                'ordering': ['user', 'order'],
                'unique_together': {('user', 'order'), ('user', 'point')},
            },
        ),
        migrations.CreateModel(
            name='StopPointProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stopped', models.BooleanField(db_index=True, default=False, help_text='Is the user currently blocked by a stoppoint?')),
                ('last_cleared', models.ForeignKey(blank=True, help_text='The last stoppoint rule this user successfully cleared.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stoppoints.stoppoint')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stoppoint_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stop Point Progress',
                'verbose_name_plural': 'User Stop Point Progresses',
            },
        ),
    ]
