# Generated by Django 5.2.3 on 2025-10-24 06:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('network', models.CharField(choices=[('TRX-20', 'TRX-20 (TRON)'), ('ERC-20', 'ERC-20 (Ethereum)'), ('BEP-20', 'BEP-20 (Binance Smart Chain)'), ('Polygon', 'Polygon (MATIC)'), ('Solana', 'Solana (SOL)'), ('Avalanche', 'Avalanche (AVAX)'), ('Fantom', 'Fantom (FTM)'), ('Arbitrum', 'Arbitrum (ARB)'), ('Optimism', 'Optimism (OP)'), ('Cardano', 'Cardano (ADA)')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet Address',
                'verbose_name_plural': 'User Wallet Addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('network', models.CharField(choices=[('TRX-20', 'TRX-20 (TRON)'), ('ERC-20', 'ERC-20 (Ethereum)'), ('BEP-20', 'BEP-20 (Binance Smart Chain)'), ('Polygon', 'Polygon (MATIC)'), ('Solana', 'Solana (SOL)'), ('Avalanche', 'Avalanche (AVAX)'), ('Fantom', 'Fantom (FTM)'), ('Arbitrum', 'Arbitrum (ARB)'), ('Optimism', 'Optimism (OP)'), ('Cardano', 'Cardano (ADA)')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Withdrawal',
                'verbose_name_plural': 'User Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('network', models.CharField(choices=[('TRX-20', 'TRX-20 (TRON)'), ('ERC-20', 'ERC-20 (Ethereum)'), ('BEP-20', 'BEP-20 (Binance Smart Chain)'), ('Polygon', 'Polygon (MATIC)'), ('Solana', 'Solana (SOL)'), ('Avalanche', 'Avalanche (AVAX)'), ('Fantom', 'Fantom (FTM)'), ('Arbitrum', 'Arbitrum (ARB)'), ('Optimism', 'Optimism (OP)'), ('Cardano', 'Cardano (ADA)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_changed_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet History',
                'verbose_name_plural': 'Wallet Histories',
                'ordering': ['-created_at'],
                'unique_together': {('address', 'network')},
            },
        ),
    ]
